from typing import AsyncIterator, Protocol


class LLMProvider(Protocol):
    async def list_models(self) -> list[dict]: ...
    async def chat_stream(self, model: str, messages: list[dict], options: dict | None = None) -> AsyncIterator[str]: ...
    async def stop_model(self, model: str) -> None: ...
