FROM node:20-alpine

WORKDIR /frontend

# Copy only package files first (better caching)
COPY frontend/package.json ./

RUN npm install

# Copy rest of frontend
COPY frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]